# Generated by Django 4.1 on 2022-08-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
