# Generated by Django 4.1 on 2022-08-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_token_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_token', to='accounts.useremail'),
        ),
    ]
