# Generated by Django 4.1 on 2022-08-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_token_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
