# Generated by Django 4.1 on 2022-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_token_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='otp',
        ),
        migrations.AddField(
            model_name='useremail',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
