# Generated by Django 4.1 on 2022-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
