# Generated by Django 4.1 on 2022-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_alter_usernotes_created_alter_usernotes_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
