# Generated by Django 4.1 on 2022-08-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_alter_usernotes_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
